---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      customize:
        cpus: 2
        memory: 1024

suites:
  - name: default
    run_list:
      - role[mysql_server]
      - role[postgresql_server]
      - role[app_server]
      - role[elasticsearch_server]
      - recipe[sugarpond_errbit]
      - recipe[journey]
      - recipe[nginx]
      - recipe[rbenv]
      - recipe[illyan]
    data_bags_path: data_bags
    encrypted_data_bag_secret_key_path: encrypted_data_bag_secret
    roles_path: roles
    attributes:
      mysql:
        ssl:
          cert_name: snakeoil-dependent
      postgresql:
        version: "9.3"
      elasticsearch:
        nginx:
          ssl:
            cert_file: /etc/ssl/certs/snakeoil-dependent.combined.crt
            key_file: /etc/ssl/certs/snakeoil-dependent.key
